FROM docker.io/gcc:12.2.0
RUN apt update
RUN apt install -y build-essential
RUN apt install -y git
RUN apt install -y cmake
RUN apt install -y gnuplot
RUN apt install -y x11-utils x11-common
RUN apt install -y libblas3-dev liblapack-dev    
RUN apt install -y libfftw3-dev
# RUN apt install xorg-devsu